// Siembro — cultivos, sistemas de riego y parámetros económicos de referencia
// Archivo cargado como script clásico: las constantes y funciones quedan globales y las usan los demás archivos.

const S=(a,b,c,d,e)=>({arenoso:a,"franco-arenoso":b,franco:c,"franco-arcilloso":d,arcilloso:e});
const METODOS={
 goteo:{n:"Goteo",ef:.9,c:9.5e6,cm:350,loc:1,txt:"Gota a gota en la raíz. Es el que más agua ahorra."},
 cinta:{n:"Cinta de goteo",ef:.88,c:5.5e6,cm:350,txt:"Goteo económico para ciclo corto; la cinta se cambia cada uno o dos ciclos."},
 micro:{n:"Microaspersión",ef:.85,c:8e6,cm:350,loc:1,txt:"Pequeños aspersores bajo cada árbol; moja toda la zona de raíces."},
 aspersion:{n:"Aspersión",ef:.75,c:6.5e6,cm:350,txt:"Lluvia artificial sobre el lote. Pierde agua con el viento y el sol del mediodía."},
 intermitente:{n:"Inundación intermitente",ef:.55,c:2.8e6,cm:60,txt:"Se inunda y se deja secar por turnos (secas y mojes). Ahorra cerca de un tercio en arroz."},
 surcos:{n:"Gravedad por surcos",ef:.5,c:1.5e6,cm:60,txt:"El agua corre por surcos o cuencas. Barato, pero gasta casi el doble que el goteo."},
 inundacion:{n:"Inundación",ef:.4,c:2.5e6,cm:60,txt:"Lámina de agua permanente. Solo para arroz y es el que más gasta."}
};
const ARB=["goteo","micro","surcos"], CIC=["cinta","aspersion","surcos"];
const C={
cacao:{n:"Cacao",g:"agr",tipo:"per",alt:[0,1200],t:[22,30],r:[1500,2800],ph:[5,7.5],s:S(.6,.85,1,1,.7),v:["CCN-51","FEAR-5","FSV-41","ICS-95","TCS-01 (Agrosavia)"],dens:1100,u:"plántulas injertadas",pS:3500,est:9e6,man:4.5e6,y:1.0,p:18000,hc:1800,ramp:[0,.15,.4,.7,.9,1,1],kc:1,met:ARB,d:"Viveros registrados ante el ICA, técnicos y jardines clonales de Fedecacao, y clones de Agrosavia. Exija el registro ICA del vivero.",nota:"Siembre con sombrío transitorio de plátano los dos primeros años; el plátano ayuda a pagar el establecimiento.",prod:"kg de grano seco"},
hass:{n:"Aguacate Hass",g:"agr",tipo:"per",alt:[1600,2500],t:[13,22],r:[1200,2000],ph:[5,7],s:S(.75,1,1,.75,.35),v:["Hass sobre patrón criollo","Hass sobre patrón antillano"],dens:280,u:"plántulas injertadas",pS:15000,est:18e6,man:9e6,y:12,p:4800,hc:250,ramp:[0,0,.15,.4,.7,.9,1],kc:.8,met:["micro","goteo","surcos"],d:"Viveros registrados ante el ICA en el Oriente antioqueño y el Eje Cafetero. Pida certificado del patrón y de la yema. Corpohass orienta sobre exportación.",nota:"Muy sensible al encharcamiento: en suelo arcilloso siembre en montículos y con drenajes. Para exportar necesita predio registrado ante el ICA.",prod:"kg de fruta"},
aguacateT:{n:"Aguacate tropical (Lorena, papelillo)",g:"agr",tipo:"per",alt:[0,1500],t:[20,30],r:[1000,2500],ph:[5,7.5],s:S(.75,1,1,.8,.4),v:["Lorena","Papelillo","Choquette","Booth 8","Santana"],dens:156,u:"plántulas injertadas",pS:10000,est:10e6,man:5e6,y:10,p:2500,hc:200,ramp:[0,0,.2,.5,.8,1,1],kc:.8,met:["micro","goteo","surcos"],d:"Viveros registrados ante el ICA de la región y Agrosavia. En la Costa hay tradición en Montes de María.",nota:"Mercado nacional; el precio baja en cosecha. Busque comprador antes de la primera cosecha.",prod:"kg de fruta"},
tabasco:{n:"Ají tabasco",g:"agr",tipo:"cic",alt:[0,1200],t:[20,32],r:[800,2000],ph:[5.5,7],s:S(.7,1,1,.85,.5),v:["Tabasco"],dens:15000,u:"plántulas de almácigo",pS:120,est:9e6,man:0,y:18,p:1700,hc:400,meses:12,ciclos:1,kc:.9,met:["goteo","cinta","aspersion","surcos"],d:"Almácigos de viveros hortícolas registrados. Lo ideal es sembrar con contrato de compra firmado con una agroindustria procesadora.",nota:"Sin contrato de compra el ají tabasco es muy riesgoso: casi todo se vende a procesadoras. La recolección manual es el costo más alto.",prod:"kg de fruto fresco"},
ajiDulce:{n:"Ají dulce (topito)",g:"agr",tipo:"cic",alt:[0,1200],t:[22,32],r:[800,2000],ph:[5.5,7],s:S(.7,1,1,.85,.5),v:["Topito","Dulce criollo"],dens:12000,u:"plántulas de almácigo",pS:150,est:8e6,man:0,y:10,p:2800,hc:350,meses:8,ciclos:1,kc:.9,met:["cinta","goteo","aspersion","surcos"],d:"Semilla de casas comerciales en almacenes agropecuarios o almácigos de viveros hortícolas.",nota:"Buen mercado en la Costa para sopas y guisos; el precio sube mucho en verano.",prod:"kg de fruto fresco"},
maiz:{n:"Maíz para grano",g:"agr",tipo:"cic",alt:[0,1800],t:[18,32],r:[800,2500],ph:[5.5,7.5],s:S(.6,.9,1,1,.8),v:["Híbrido amarillo","Híbrido blanco","Variedad criolla"],dens:65000,u:"semillas",pS:11,est:5.8e6,man:0,y:6.5,p:1250,hc:60,meses:4,ciclos:2,kc:.85,met:CIC,d:"Híbridos certificados en almacenes agropecuarios. Fenalce y la UMATA dan asistencia técnica.",nota:"Margen estrecho: gana quien tiene buen rendimiento y vende a buen precio. Revise el precio de compra en la zona antes de sembrar.",prod:"kg de grano seco"},
yuca:{n:"Yuca",g:"agr",tipo:"cic",alt:[0,1800],t:[20,32],r:[800,2500],ph:[4.5,7],s:S(1,1,.9,.7,.35),v:["Venezolana","Corpoica Tai","Criolla de mesa"],dens:12500,u:"estacas",pS:150,est:4.5e6,man:0,y:18,p:750,hc:80,meses:10,ciclos:1,kc:.7,met:CIC,d:"Estacas sanas de cultivos conocidos o semilla mejorada de Agrosavia. No use estacas de lotes enfermos.",nota:"Cultivo rústico y resistente a sequía; necesita suelo suelto. En suelo pesado la raíz se pudre.",prod:"kg de raíz"},
name:{n:"Ñame",g:"agr",tipo:"cic",alt:[0,800],t:[25,32],r:[1000,2000],ph:[5.5,7],s:S(.8,1,1,.7,.35),v:["Espino","Diamante 22"],dens:2000,u:"kg de semilla",pS:1800,est:7e6,man:0,y:15,p:1600,hc:100,meses:9,ciclos:1,kc:.85,met:CIC,d:"Semilla de productores reconocidos de la región y de Agrosavia (centro Turipaná, en Cereté).",nota:"Cultivo típico de Córdoba, Sucre y Bolívar. La semilla es el costo más alto; guarde la suya para el siguiente ciclo.",prod:"kg de tubérculo"},
platano:{n:"Plátano",g:"agr",tipo:"per",alt:[0,1600],t:[20,32],r:[1500,3000],ph:[5.5,7.5],s:S(.6,.9,1,1,.6),v:["Hartón","Dominico hartón"],dens:1600,u:"colinos",pS:1500,est:6e6,man:7e6,y:16,p:1300,hc:120,ramp:[.5,1,1,1,.9,.9,.85],kc:1.1,met:["micro","goteo","aspersion","surcos"],d:"Colinos de viveros registrados ante el ICA o plantas in vitro de laboratorios registrados. Evite colinos de fincas con moko o Fusarium.",nota:"Produce desde el primer año y da flujo de caja constante. Muy exigente en agua.",prod:"kg de racimo"},
cafe:{n:"Café",g:"agr",tipo:"per",alt:[1200,2000],t:[17,23],r:[1600,2500],ph:[4.5,6],s:S(.6,.9,1,1,.7),v:["Castillo","Cenicafé 1","Tabi"],dens:5000,u:"chapolas",pS:600,est:12e6,man:8e6,y:1.8,p:15000,hc:3500,ramp:[0,.3,.9,1,1,.95,.9],kc:.95,met:["goteo","micro"],d:"Semilla certificada de Cenicafé a través del Comité de Cafeteros de su municipio, que también da asistencia técnica.",nota:"El precio depende de la bolsa de Nueva York y del dólar. La recolección es el costo principal.",prod:"kg de café pergamino seco"},
papa:{n:"Papa",g:"agr",tipo:"cic",alt:[2400,3300],t:[8,16],r:[700,1500],ph:[5,6.5],s:S(.7,1,1,.8,.45),v:["Diacol Capiro","Pastusa Suprema","Criolla Colombia"],dens:2000,u:"kg de semilla",pS:2200,est:18e6,man:0,y:28,p:1000,hc:40,meses:5,ciclos:2,kc:.9,met:["aspersion","cinta","surcos"],d:"Semilla certificada ICA en distribuidores autorizados. No siembre papa de consumo como semilla.",nota:"El precio de la papa sube y baja mucho: en una cosecha se gana y en otra se pierde. Mire el ciclo de precios antes de sembrar.",prod:"kg de tubérculo"},
limon:{n:"Limón Tahití",g:"agr",tipo:"per",alt:[0,1400],t:[22,32],r:[1000,2000],ph:[5.5,7.5],s:S(.7,1,1,.8,.4),v:["Tahití sobre patrón Sunki","Tahití sobre patrón Volkameriana"],dens:400,u:"plántulas injertadas",pS:9000,est:8e6,man:7e6,y:25,p:1500,hc:120,ramp:[0,.15,.5,.8,1,1,1],kc:.7,met:["micro","goteo","surcos"],d:"Viveros registrados ante el ICA con patrón y yema certificados (exija certificado libre de HLB).",nota:"Hay mercado de exportación; con riego puede programar la cosecha para los meses de mejor precio.",prod:"kg de fruta"},
maracuya:{n:"Maracuyá",g:"agr",tipo:"per",alt:[0,1300],t:[21,32],r:[800,1800],ph:[5.5,7],s:S(.7,1,1,.8,.45),v:["Amarillo"],dens:800,u:"plántulas",pS:1500,est:12e6,man:10e6,y:18,p:2200,hc:200,ramp:[.5,1,.6,.5,1,.6,.5],kc:.85,met:["goteo","surcos"],d:"Viveros registrados ante el ICA o semilla seleccionada de frutos sanos.",nota:"Se renueva cada 2 a 3 años (el cálculo incluye la renovación). Necesita espaldera y polinización.",prod:"kg de fruta"},
frijol:{n:"Fríjol",g:"agr",tipo:"cic",alt:[1200,2500],t:[15,24],r:[800,1600],ph:[5.5,7],s:S(.6,1,1,.8,.4),v:["Cargamanto","Radical","Bola roja"],dens:60,u:"kg de semilla",pS:9000,est:7e6,man:0,y:1.6,p:5500,hc:500,meses:4,ciclos:2,kc:.8,met:["aspersion","cinta","surcos"],d:"Semilla certificada en almacenes agropecuarios y variedades mejoradas de Agrosavia.",nota:"Sensible al exceso de lluvia en cosecha. Muy común en el Oriente y el Suroeste de Antioquia.",prod:"kg de grano seco"},
papaya:{n:"Papaya",g:"agr",tipo:"per",alt:[0,1000],t:[22,32],r:[1200,2200],ph:[5.5,7],s:S(.7,1,1,.75,.35),v:["Tainung","Maradol"],dens:1600,u:"plántulas",pS:1200,est:6e6,man:12e6,y:45,p:1100,hc:100,ramp:[.5,1,.7,.5,1,.7,.5],kc:1,met:["goteo","micro","surcos"],d:"Semilla híbrida en almacenes agropecuarios o plántulas de viveros registrados.",nota:"Produce rápido pero sufre virosis: se renueva cada 2 a 3 años (incluido en el cálculo).",prod:"kg de fruta"},
tomateArbol:{n:"Tomate de árbol",g:"agr",tipo:"per",alt:[1800,2600],t:[14,20],r:[1000,2000],ph:[5.5,7],s:S(.7,1,1,.8,.45),v:["Común","Amarillo","Rojo"],dens:1100,u:"plántulas",pS:1500,est:7e6,man:10e6,y:30,p:1600,hc:150,ramp:[.3,1,.9,.6,.3,1,.9],kc:.85,met:["goteo","surcos"],d:"Viveros registrados ante el ICA del Oriente y Norte antioqueño.",nota:"Se renueva cada 3 a 4 años (incluido en el cálculo). Muy atacado por antracnosis en épocas lluviosas.",prod:"kg de fruta"},
arroz:{n:"Arroz de riego",g:"agr",tipo:"cic",alt:[0,800],t:[24,33],r:[800,3000],ph:[5,7.5],s:S(.3,.5,.8,1,1),v:["Variedad Fedearroz recomendada para su zona"],dens:150,u:"kg de semilla",pS:4500,est:8.5e6,man:0,y:7,p:1500,hc:50,meses:4,ciclos:2,kc:1.15,perc:1.25,soloRiego:true,met:["intermitente","inundacion"],d:"Semilla certificada en distribuidores autorizados. Fedearroz da asistencia técnica y le dice qué variedad sirve en su zona.",nota:"Es el cultivo que más agua gasta. Con nivelación del lote e inundación intermitente se ahorra cerca de un tercio. Sin agua segura no lo siembre.",prod:"kg de arroz paddy verde"},
pastoT:{n:"Pastos de clima cálido",g:"for",tipo:"pasto",alt:[0,1800],t:[20,32],r:[800,3000],ph:[4.5,7],s:S(.8,.9,1,1,.8),v:["Brachiaria decumbens","Brachiaria brizantha (Toledo)","Mombasa","Angleton","Cuba OM-22 (pasto de corte)"],dens:6,u:"kg de semilla",pS:85000,est:3.5e6,man:1.2e6,y:18,pCarne:9000,pLeche:1900,gdp:.45,leche:5,cL:950,ramp:[.5,1,1,1,1,1,1,1],kc:.85,met:["aspersion","surcos"],d:"Semilla certificada en almacenes agropecuarios. Fedegán, Agrosavia y la UMATA asesoran en pastos mejorados y división de potreros.",nota:"No incluye la compra de los animales. Divida en potreros con cerca eléctrica y rote: así se logra la carga animal del cálculo.",prod:"t de materia seca"},
pastoF:{n:"Pastos de clima frío (kikuyo, ryegrass)",g:"for",tipo:"pasto",alt:[1800,3200],t:[10,20],r:[800,2200],ph:[5,6.8],s:S(.7,1,1,.9,.7),v:["Kikuyo","Ryegrass","Kikuyo con trébol"],dens:30,u:"kg de semilla",pS:22000,est:3e6,man:2.5e6,y:15,pCarne:9000,pLeche:1900,gdp:.5,leche:14,cL:1250,ramp:[.6,1,1,1,1,1,1,1],kc:.85,met:["aspersion","surcos"],d:"Semilla certificada en almacenes agropecuarios. Fedegán y Agrosavia asesoran en praderas para lechería.",nota:"Zona de lechería especializada (Norte y Oriente de Antioquia, altiplano). No incluye la compra de los animales.",prod:"t de materia seca"},
maizF:{n:"Maíz forrajero (ensilaje)",g:"for",tipo:"cic",alt:[0,2600],t:[14,32],r:[600,2000],ph:[5.5,7.5],s:S(.6,.9,1,1,.8),v:["Híbrido forrajero","Híbrido de doble propósito"],dens:70000,u:"semillas",pS:11,est:7e6,man:0,y:45,p:320,hc:60,meses:4,ciclos:2,kc:.9,met:CIC,d:"Híbridos forrajeros en almacenes agropecuarios. Para ensilar necesita picadora y bolsas o un silo de trinchera.",nota:"Siémbrelo en lluvias y ensílelo para el verano.",prod:"kg de forraje verde (silo)",silo:true},
sorgoF:{n:"Sorgo forrajero",g:"for",tipo:"cic",alt:[0,1800],t:[20,35],r:[400,1500],ph:[5.5,8],s:S(.7,.95,1,1,.85),v:["Sorgo forrajero híbrido","Sorgo dulce"],dens:15,u:"kg de semilla",pS:18000,est:5e6,man:0,y:40,p:260,hc:50,meses:4,ciclos:2,kc:.8,met:CIC,d:"Semilla en almacenes agropecuarios. Fenalce y Agrosavia asesoran en manejo.",nota:"Aguanta más la sequía que el maíz y rebrota después del corte. Muy bueno para el verano en la Costa.",prod:"kg de forraje verde (silo)",silo:true},
millo:{n:"Millo (sorgo para grano)",g:"for",tipo:"cic",alt:[0,1500],t:[22,35],r:[400,1500],ph:[5.5,8],s:S(.7,.95,1,1,.85),v:["Sorgo granífero híbrido"],dens:10,u:"kg de semilla",pS:14000,est:3.9e6,man:0,y:4.2,p:1150,hc:60,meses:4,ciclos:2,kc:.8,met:CIC,d:"Semilla certificada en almacenes agropecuarios. Fenalce da asistencia técnica.",nota:"En la Costa se le dice millo. Gasta menos agua que el maíz y se vende a fábricas de concentrado o se usa en la finca para los animales.",prod:"kg de grano"}
};
const MODOS={trad:"Tradicional",riego:"Con riego",auto:"Automatizado"};
